# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

# Parameters
nc: 1  # number of classes
depth_multiple: 0.33  # model depth multiple
width_multiple: 0.50  # layer channel multiple

#depth_multiple: 0.67  # model depth multiple
#width_multiple: 0.75  # layer channel multiple

#depth_multiple: 1.33  # model depth multiple
#width_multiple: 1.25  # layer channel multiple

anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
#  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 v6.0 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 6, 2, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 1, PanicleC3_1 , [128,128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 1, PanicleC3_1, [256,256]],#
   [-1, 1, SELayer, [256,256]],

   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 1, PanicleC3_1, [512,512]],
   [-1, 1, SELayer, [512,512]],

   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, PanicleC3_1, [1024,1024]],
   [-1, 1, SPPF, [1024, 5]],  # 9
   [-1, 1, SELayer, [1024,1024]],
  ]
#
# YOLOv5 v6.0 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 8], 1, Concat, [1]],  # cat backbone P4
   [-1, 1, PanicleC3_2, [512,512]],  # 13

   [-1, 1, Conv, [256, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 5], 1, Concat, [1]],  # cat backbone P3
   [-1, 1, PanicleC3_2, [512,512]],  # 17 (P3/8-smallxml)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 17], 1, Concat, [1]],  # cat head P4
   [-1, 1, PanicleC3_2, [512,512]],  # 20 (P4/16-medium)

#   [-1, 1, Conv, [512, 3, 2]],
#   [[-1, 10], 1, Concat, [1]],  # cat head P5
#   [-1, 1, C3, [1024, False]],  # 23 (P5/32-large)

   [[20,23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]

